### ISSUE TITLE
Adding Code of Conduct file

### ISSUE THREAD

**Issue by aakankshabhende** [sameersrivastava13/Vaccine-Tracker-App#10]
Creating a Code of Conduct which everyone must abide by and mentioning the Scope of this Code of Conduct.

**Comment by sameersrivastava13** [comment]
Hi @aakankshabhende. I believe we already have that in our project, please check once. If not, then I'll assign this issue to you.

**Comment by aakankshabhende** [comment]
No @sameersrivastava13 sir, code of conduct file is not there.

**Comment by sameersrivastava13** [comment]
okay then @aakankshabhende. Go ahead.
