### ISSUE TITLE
Add Contributors Details 

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#100]
### Description
 
We have the project [contributors page](https://vaccine-tracker-app.netlify.app/aboutus.html) ready with us . All contributors who have previously contributed to the project, add your name, photograph, GitHub and LinkedIn link. 
 
**_Only for all those who contributed to the project previously._**

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

**Comment by sameersrivastava13** [comment]
@ayushsoni1010 go ahead.

**Comment by SukhbirSinghKhalsa** [comment]
![sukhbir](https://user-images.githubusercontent.com/58480511/127379571-9df41fc7-b74f-4176-b2ca-052e5c89e7c5.jpg)

Name: 
Sukhbirsingh Khalsa
Github: 
https://github.com/SukhbirSinghKhalsa/
Linkedin: https://www.linkedin.com/in/sukhbirsinghkhalsa/

**Comment by anupamishra333** [comment]
@sameersrivastava13 wanted to add my infomation.

**Comment by sameersrivastava13** [comment]
@anupamishra333 Go ahead. Submit PR.

**Comment by deed-pooL** [comment]
Hey, where should I add my details?

**Comment by sameersrivastava13** [comment]
> Hey, where should I add my details?

[contributors page](https://vaccine-tracker-app.netlify.app/aboutus.html) @deed-pooL .
Take help from @anupamishra333 on slack.

**Comment by anupamishra333** [comment]
@deed-pooL kindly see file changes in my pull request , do the same here is link of my PR:- 
https://github.com/sameersrivastava13/Vaccine-Tracker-App/pull/106/files

**Comment by Sayan-15** [comment]
favicon was submitted, and it was successfully merged too. How ,I have to submit the name, id and photo? With PR request? or any google form is there?

**Comment by anupamishra333** [comment]
You have to edit code for it. There is no google form. @Sayan-15
