### ISSUE TITLE
Adding my avatar in the contributor's page

### ISSUE THREAD

**Issue by ayushsoni1010** [sameersrivastava13/Vaccine-Tracker-App#103]
**Description**
Heyy @sameersrivastava13 👋

I want to add my avatar in the contributor's page.
As I have contributed to this project, So I would like to add.

**Solution**
PR got merged + name in the score sheet

**Comment by sameersrivastava13** [comment]
Yes go ahead @ayushsoni1010. Am closing this issue as I have already created one. #100
