### ISSUE TITLE
Create an Issue & Pull Request Template

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#11]
### AIM
Create a custom Issue and Pull Request Template.

### Features
Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.

Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

**Comment by manoj-015** [comment]
Sir, @Sejal2801 @sameersrivastava13 can i work through this issue?

**Comment by sameersrivastava13** [comment]
Sure @MANOJ-015. I am assigning it to you. Go ahead.

**Comment by MANOJ-015** [comment]
Thank you sir, the pull request is merged. but, the issue template file i.e, `issue_template.md`  should be added into :  
`settings << issues << custom template ` of the project, inorder use the template.
