### ISSUE TITLE
Create the Web App UI Design

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#12]
### AIM
Create the Web UI Design in a widely-supported Design Software (Adobe XD/Figma).

### Details
We are currently looking for two pages: (Or we can also make a single page application)

**Landing Page:** An attractive Landing Page which outlines the purpose of the Project and what it aims to achieve. The landing page will have a input form. This form contains only two required input field, that takes pincode as input from the user and date field that will be used to get data from the api.
**Result Page:** The Result is either presented in card form or table form. The vaccine slots that are available in the provided pincode on a particular date. For e.g : visit [Example 1](https://apps.healthifyme.com/vaccinateme/?type=district), [Example 2](https://apps.healthifyme.com/vaccinateme/?type=district)

### Contributors Guideline
One can work on one or more pages at a given time. Ask yourself to be assigned that Issue, so that you can make the PR.
Submissions should be made in an apt form so that Web Developers can work on them seamlessly.
The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

**Comment by dilroseR** [comment]
> ### AIM
> Create the Web UI Design in a widely-supported Design Software (Adobe XD/Figma).
> 
> ### Details
> We are currently looking for two pages: (Or we can also make a single page application)
> 
> **Landing Page:** An attractive Landing Page which outlines the purpose of the Project and what it aims to achieve. The landing page will have a input form. This form contains only two required input field, that takes pincode as input from the user and date field that will be used to get data from the api.
> **Result Page:** The Result is either presented in card form or table form. The vaccine slots that are available in the provided pincode on a particular date. For e.g : visit [Example 1](https://apps.healthifyme.com/vaccinateme/?type=district), [Example 2](https://apps.healthifyme.com/vaccinateme/?type=district)
> 
> ### Contributors Guideline
> One can work on one or more pages at a given time. Ask yourself to be assigned that Issue, so that you can make the PR.
> Submissions should be made in an apt form so that Web Developers can work on them seamlessly.
> The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.

Can we do this with simple html, css and bootstrap?

**Comment by dilroseR** [comment]
i'll try working on Landing page 
Assign it to me

**Comment by sameersrivastava13** [comment]
> > ### AIM
> > Create the Web UI Design in a widely-supported Design Software (Adobe XD/Figma).
> > ### Details
> > We are currently looking for two pages: (Or we can also make a single page application)
> > **Landing Page:** An attractive Landing Page which outlines the purpose of the Project and what it aims to achieve. The landing page will have a input form. This form contains only two required input field, that takes pincode as input from the user and date field that will be used to get data from the api.
> > **Result Page:** The Result is either presented in card form or table form. The vaccine slots that are available in the provided pincode on a particular date. For e.g : visit [Example 1](https://apps.healthifyme.com/vaccinateme/?type=district), [Example 2](https://apps.healthifyme.com/vaccinateme/?type=district)
> > ### Contributors Guideline
> > One can work on one or more pages at a given time. Ask yourself to be assigned that Issue, so that you can make the PR.
> > Submissions should be made in an apt form so that Web Developers can work on them seamlessly.
> > The task is open to creativity. You can combine modern UI/UX philosophies to come up with your own design.
> 
> Can we do this with simple html, css and bootstrap?

Yes @dilroseR . Actually we will be using html, CSS and bootstrap only to build the frontend of our application.

**Comment by sameersrivastava13** [comment]
> i'll try working on Landing page
> Assign it to me

ok @dilroseR. Assigning it to you. Go ahead.
