### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by payaldutta** [sameersrivastava13/Vaccine-Tracker-App#16]
I want to add labels and a point table in the readme.md file for those who are new in open source.
@sameersrivastava13  can I work on this issue under DCP'21.

**Comment by sameersrivastava13** [comment]
@payaldutta What kind of labels & point table you want to add? Please can you provide few more details or an example to get better idea whether its needed or not.

**Comment by swathi-469** [comment]
Can I Work on this issue please assign this to me I am a beginner so it would easy to start

**Comment by sameersrivastava13** [comment]
> Can I Work on this issue please assign this to me I am a beginner so it would easy to start

Hi @swathi-469 . Actually this issue is created by @payaldutta. Therefore she will be working on this after she provides me details about the feature she is going to add. You can look for some other beginner issues or can wait as I will be creating many more issues soon.

**Comment by swathi-469** [comment]
Ohh kk I will wait for some beginner friendly issues.
