### ISSUE TITLE
Fixing error in Readme.md file

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#18]
## Actual Behavior

Currently there is an extra java logo in the `readme.md` file which is not required in the `readme.md` file. As we have a different tech stack.

## Steps to close the Issue

To close this issue, fix the error by removing the java logo and adding a flask logo in place of that. Also links are not properly defined for html, CSS, Bootstrap, flask and JavaScript. You need to fix both of them in order to close this issue.

## Check List (check only one)

- [ ] Creating New Script.
- [x] Enhacment to Older script.

### Where the Correction is needed:

![Capture](https://user-images.githubusercontent.com/56088741/125181917-1cd11b00-e227-11eb-80e2-3cba75c5fb22.PNG)

**Comment by Ritika-Agrawal811** [comment]
I would like to work on this issue as part of devincept contribution programme. Please assign this issue to me.

**Comment by sameersrivastava13** [comment]
@Ritika-Agrawal811 Assigning it to you. Go ahead.

**Comment by sameersrivastava13** [comment]
@Ritika-Agrawal811 any updates?

**Comment by Prakash-Haldar** [comment]
If No one is contributing to this issue , can I proceed for this @sameersrivastava13

**Comment by Ritika-Agrawal811** [comment]
> @Ritika-Agrawal811 any updates?

I am done. Just making my pull request in a few minutes.

**Comment by sameersrivastava13** [comment]
> > @Ritika-Agrawal811 any updates?
> 
> I am done. Just making my pull request in a few minutes.

No issues take your time @Ritika-Agrawal811.

**Comment by sameersrivastava13** [comment]
> If No one is contributing to this issue , can I proceed for this @sameersrivastava13

Don't worry @Prakash-Haldar . I'll be creating more issues tomorrow you can take those if you want. Till then you can explore other available issues.

**Comment by Ritika-Agrawal811** [comment]
@sameersrivastava13 I have made a PR. Could you look into it?

**Comment by sameersrivastava13** [comment]
> @sameersrivastava13 I have made a PR. Could you look into it?

I have requested few changes please check once. @Ritika-Agrawal811
