### ISSUE TITLE
Create a basic Setup for the application

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#19]
**### Type**
Feature/Advancement

**### Description**
 Create a Folder named templates which consists of three HTML Pages. Add mock HTML Code in them to serve them from the Flask App.

1. Landing Page
2. Vaccine Tracker using pincode
3. Vaccine Tracker using district name

 Create a Folder named `Static` to serve Static Content and other Assets.
 Link Style and Script to the HTML Code.

### **Tools**
HTML
CSS
Javascript
Python

**### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?**
Yes

### Motivation
To set a basic boilerplate for our application before we move ahead with the Development Part.

**Comment by MANOJ-015** [comment]
Sir, @sameersrivastava13 @Sejal2801 Can i work through this issue?

**Comment by MANOJ-015** [comment]
Sir, Can i work through the issue?

**Comment by MANOJ-015** [comment]
Sir, @sameersrivastava13 @Sejal2801 Can i Work through the issue?
and what should be file names of  three html files

**Comment by NagaSudheer-123** [comment]
Please, assign this...I am interested in taking this issue.

**Comment by sameersrivastava13** [comment]
Assigned @NagaSudheer-123. Go ahead.

**Comment by sameersrivastava13** [comment]
@NagaSudheer-123 any updates?
