### ISSUE TITLE
Add Documentation on setting Flask

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#21]
### **Type**
Advancement

### Description
Create a Documentation File using Markdown and add it into a specific Documentation/ directory to allow new contributors to get started with setting Flask. The features to be added in the documentation includes:

- Give a basic idea about Flask as a Micro Web-Framework.
- Give a step-wise plan of setting Flask on Windows/Linux/OSX Environment.
- Add Screenshots wherever possible.
- Add a sample Flask Code with a mock endpoint to show the Server up and running.

### **Tools**
Markdown
Python
Pip/Conda

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

### Motivation
To contribute to the Wiki of this Project in the longer run.

**Comment by Satishcsg** [comment]
I was interested to contribute. Please assign this task.

**Comment by sameersrivastava13** [comment]
Go ahead @Satishcsg . Assigning you the issue.

**Comment by Satishcsg** [comment]
could you tel me where would I have to include documentation file in the project ?

**Comment by Satishcsg** [comment]
Could you tell me where would I have to include this markdown file ? Is it like create a new folder and and placing the md file in that folder. If it so, what name should be given to that folder ?
