### ISSUE TITLE
Design a Page for project Contributors + Admin + Mentors

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#26]
### Type
Advancement

### Description
Design a Page using a UI Prototyping Tool like Adobe XD/Figma, for the Project Contributors, Mentors and Project admin. Make sure to submit the design in Image/PDF Format along with the raw file in the appropriate design/ directory. The page should have two parts:

Project Admin and Mentors
Contributors

You can use Dummy Data for the designing part.

### Tools
Adobe XD/Figma

**Comment by nirban07** [comment]
Hi @sameersrivastava13 i would like to help ....assign this issue to me

**Comment by deed-pooL** [comment]
@sameersrivastava13 Assign me this, I will finish this by 17th July .
Thanks

**Comment by sameersrivastava13** [comment]
Great @deed-pooL & @nirban07 you both can work on this issue. Go ahead.

**Comment by sameersrivastava13** [comment]
@deed-pooL & @nirban07  any updates?
