### ISSUE TITLE
Addition of Project maintainer in readme.md 

### ISSUE THREAD

**Issue by PrathmeshMutke** [sameersrivastava13/Vaccine-Tracker-App#29]
Hi there,
I want to add Project maintainer feature in readme.md file
please assign me this issue.

**Comment by sameersrivastava13** [comment]
ok @PrathmeshMutke. I will assign you this issue. But first complete the previous issue assigned to you. Get that successfully merged and then I'll assign you this issue.

**Comment by sameersrivastava13** [comment]
@PrathmeshMutke Assigning you the issue.

**Comment by sameersrivastava13** [comment]
@PrathmeshMutke Any updates?

**Comment by deed-pooL** [comment]
I am interested, kindly assign this task to me

**Comment by sameersrivastava13** [comment]
> I am interested, kindly assign this task to me

Assigning it to you @deed-pooL. Go ahead. You have 24 hours to complete and submit the PR.

**Comment by deed-pooL** [comment]
Please provide me with any specific details if you have. I will complete
the task by 15th july.

**Comment by sameersrivastava13** [comment]
> Please provide me with any specific details if you have. I will complete the task by 15th July.
 
For now you can just add heading `(Project maintainer)`, my name, and photograph. All these you can find in my profile. Take reference from other readme files.

**Comment by deed-pooL** [comment]
Sure, will do that.
