### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by anupamishra333** [sameersrivastava13/Vaccine-Tracker-App#34]
Can I add a Scroll to the top button on this website?

**Comment by sameersrivastava13** [comment]
@anupamishra333 Yes you can but right now the front end of our web app is not ready. @dilroseR and @purohitmansi are working on building the front end of our application.
So you can wait and later on when it is ready I'll assign it to you. Till then you can explore other available issues.

**Comment by anupamishra333** [comment]
ohk no issue @sameersrivastava13

**Comment by Biswa-bob** [comment]
Can i work on this issue please !!

**Comment by anupamishra333** [comment]
@Biswa-pop This issue is on hold and I already created this feature so please try to work on different as I am also doing work on another

**Comment by anupamishra333** [comment]
@Biswa-pop This issue is on hold and I already created this feature so please try to work on different as I am also doing work on another

**Comment by anupamishra333** [comment]
@Biswa-pop This issue is on hold and I already created this feature so please try to work on different as I am also doing work on another

**Comment by Biswa-bob** [comment]
@anupamishra333 Actually I have used this feature in my previous project so I wanted to help

**Comment by sameersrivastava13** [comment]
@Biswa-bob & @anupamishra333 today only we got our front end ready. Please have a look by either cloning or downloading the files. See what improvements can you both do in that as according to me many improvements are required. It is not responsive also I guess therefore if you can make it responsive first and then add the scroll to top and other features. It will be great.

**Comment by anupamishra333** [comment]
can u assign me i am working on this now

**Comment by sameersrivastava13** [comment]
ok @anupamishra333. Go ahead
