### ISSUE TITLE
Add a Footer for the application

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#37]
### Type
Enhancement

### Description
Add a basic footer with copyright symbol. Also you can add a text like `Made with ❤️ for the people of India.`

### Tools
HTML
CSS

**Comment by AmruthaCK** [comment]
Can I work on this issue under DCP'21

**Comment by sameersrivastava13** [comment]
Awesome @AmruthaCK. Go ahead.

**Comment by Amrutha1101** [comment]
Sorry, that was my another account

**Comment by Amrutha1101** [comment]
Can I work on the issue?

**Comment by sameersrivastava13** [comment]
> Can I work on the issue?

Yes @Amrutha1101. Go ahead.
