### ISSUE TITLE
Add a responsive navigation bar

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#38]
### Description
Add a responsive navigation bar for the application. The items that are to be included in the navigation bar are:

1. Name of the application (Vaccine Tracker)
2. Home
3. Search by Pincode
4. Search by District Name
5. Contact

### Tools
HTML
CSS

**Comment by Biswa-bob** [comment]
Can I work on this please

**Comment by sameersrivastava13** [comment]
@Biswa-bob go ahead. Assigned.

**Comment by Biswa-bob** [comment]
![nav-f](https://user-images.githubusercontent.com/56729624/125742892-b22e571d-6bff-4e6a-92d0-b130bc15af9b.png)

IS this design alright?

**Comment by Biswa-bob** [comment]
![nav-s](https://user-images.githubusercontent.com/56729624/125743158-828f79c3-fcc6-4874-b16b-cd2a97960245.png)

For small Screen

**Comment by Biswa-bob** [comment]
![nav-s1](https://user-images.githubusercontent.com/56729624/125750661-c16d304f-37ce-466f-a0e6-7c4b5038f36e.png)
![nav-s2](https://user-images.githubusercontent.com/56729624/125750668-345d858d-b3dc-4ad5-9b7c-f7537917141a.png)


For Small Screen

**Comment by sameersrivastava13** [comment]
Looks quite good @Biswa-bob. Please have a look at this [navigation bar](https://www.sanjeevaniportal.xyz/vaccinetrackerbypincode). Can you please try making the nav. bar like this?

**Comment by Biswa-bob** [comment]
![head-f](https://user-images.githubusercontent.com/56729624/125808698-7bba2c56-ee04-4c90-86d0-5b1d99eac58e.png)

Full Size screen

![head-s](https://user-images.githubusercontent.com/56729624/125808740-03101f9b-0226-4a69-9c15-20869d867d19.png)

Small Size screen

**Comment by sameersrivastava13** [comment]
Awesome @Biswa-bob. Looks good to me now. What are your thoughts @Sejal2801 ?

**Comment by sameersrivastava13** [comment]
Just do one more thing @Biswa-bob. Replace `oxygen`  to `Latest news` or `News`.  Now you can make the changes and submit the PR. Will review it there now.

**Comment by Sejal2801** [comment]
> Awesome @Biswa-bob. Looks good to me now. What are your thoughts @Sejal2801 ?

Its Awesome. Looks good to me also

**Comment by Biswa-bob** [comment]
done and ready to push

**Comment by Sejal2801** [comment]
Have you made changes?

**Comment by Sejal2801** [comment]
If you have made then please submit the PR

**Comment by Biswa-bob** [comment]
Done please review it
