### ISSUE TITLE
Login-signup page

### ISSUE THREAD

**Issue by shivshankar9** [sameersrivastava13/Vaccine-Tracker-App#4]
Setup login-sign up page

**Comment by TheArushiSingh** [comment]
I'm interested in working on it.
 You can assign it to me.

**Comment by NikhilSharma03** [comment]
@sameersrivastava13 Can i work on that. We can use reactJS.

**Comment by sameersrivastava13** [comment]
hello @shivshankar9  & @NikhilSharma03, Actually in this project we don't need any sign up or login page. Other information regarding the project will be shared soon with you all. So am closing this issue.
