### ISSUE TITLE
Making the header Responsive 

### ISSUE THREAD

**Issue by Biswa-bob** [sameersrivastava13/Vaccine-Tracker-App#40]
## Actual Behavior

The Header is not Responsive

## Steps to close the Issue

 By Creating a container and adding columns.

## Specifications

  - Language Used: HTML,CSS

**Comment by sameersrivastava13** [comment]
Awesome @Biswa-bob. You can work on this issue. But just now I have assigned you another issue. Complete that first, submit the PR come back here and I'll assign it to you.

**Comment by sameersrivastava13** [comment]
ok @Biswa-bob. I am assigning this issue to you. You can continue working on both the issues and submit PR solving both nav bar and this one. Will give you score for solving both of them. Go ahead.
