### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by kumarishalini6** [sameersrivastava13/Vaccine-Tracker-App#45]
@sameersrivastava13  i want to make custom scrollbar.
can i work on this issue??

**Comment by sameersrivastava13** [comment]
@kumarishalini6 Already assigned you another issue. Please complete that first then I will assign it to you.

**Comment by kumarishalini6** [comment]
Ok

**Comment by SukhbirSinghKhalsa** [comment]
Can I know where custom scroll bar is needed ?

**Comment by kumarishalini6** [comment]
@sameersrivastava13  i have completed my task now can you assign me??

**Comment by sameersrivastava13** [comment]
@kumarishalini6 Go ahead.
