### ISSUE TITLE
Add img bot 

### ISSUE THREAD

**Issue by ayushsoni1010** [sameersrivastava13/Vaccine-Tracker-App#49]
**Is your feature request related to a problem? Please describe.**
Adding an image bot to the project will help us optimize images

**Describe the solution you'd like**
Any Project Admin can add this through this link: https://github.com/marketplace/imgbot

**Screenshots**
![image](https://user-images.githubusercontent.com/76895975/125985323-c07c4e91-cc94-4119-bb4b-2fd1f4184020.png)

**Comment by sameersrivastava13** [comment]
Yes much needed @ayushsoni1010 . Are you willing to take it and complete?

**Comment by ayushsoni1010** [comment]
Sure @sameersrivastava13 :)

**Comment by sameersrivastava13** [comment]
ok @ayushsoni1010. Assigning it to you.
