### ISSUE TITLE
Designing application & parallex scrolling effect

### ISSUE THREAD

**Issue by aishwaryas15** [sameersrivastava13/Vaccine-Tracker-App#5]

**Comment by sameersrivastava13** [comment]
Hi @aishwaryas15 can you please provide few more details or a demo that I can see and assign it to you.

**Comment by aishwaryas15** [comment]
Shall I attach a screenshot? So u can get it?

**Comment by sameersrivastava13** [comment]
Yes please @aishwaryas15.

**Comment by aishwaryas15** [comment]
https://user-images.githubusercontent.com/62896706/125332007-56f50680-e366-11eb-92ad-a14a02f4df2d.mp4

this is just a example i made

**Comment by sameersrivastava13** [comment]
Looks great @aishwaryas15. I am assigning you the issue. Start working on designing the application & adding parallex scrolling effect. We also have one [UI design](https://github.com/sameersrivastava13/Vaccine-Tracker-App/tree/main/Front-end_UI) ready with us. Please have a look and try designing the application according to that if possible. OR if you have another design then you can show that as well.

**Comment by sameersrivastava13** [comment]
@aishwaryas15 Updates?

**Comment by aishwaryas15** [comment]
Yeah sorry.By tonight I'll submit it
