### ISSUE TITLE
Updating Readme 

### ISSUE THREAD

**Issue by ayushsoni1010** [sameersrivastava13/Vaccine-Tracker-App#50]
**Is your feature request related to a problem? Please describe.**
Adding Website and Playstore link

**Describe the solution you'd like**
Updating Readme.md file by adding links as this project got deployed and adding a logo type image

**Screenshots**
![image](https://user-images.githubusercontent.com/76895975/125994406-dfd4e744-e845-4590-b1f9-f1174b8d31b3.png)

**Comment by ayushsoni1010** [comment]
Sorry, it was bi-mistakenly mentioned this issue here (Img Bot Added)

**Comment by sameersrivastava13** [comment]
Go ahead @ayushsoni1010. Assigned.
