### ISSUE TITLE
Add a Preloader

### ISSUE THREAD

**Issue by ayushsoni1010** [sameersrivastava13/Vaccine-Tracker-App#55]
**Is your feature request related to a problem? Please describe.**
When a user used to open a website, it would load completely and looks pretty.

**Describe the solution you'd like**
Adding a preloader would help us to load graphics and all content.

**Comment by kumarishalini6** [comment]
if no one is working can i work on this issue??

**Comment by sameersrivastava13** [comment]
Go ahead @ayushsoni1010. Assigning it to you. Make sure the pre loader `(If you will be using any gif or something)` is related to the theme of the project.
