### ISSUE TITLE
Fixing the contribution Guidelines 

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#57]
### Description
The contribution Guidelines in the readme file has many issues that needs to be fixed asap. Like the Screen shots( need cropped images) and `master` has to be replaced with `main`.

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

**Comment by sufu786** [comment]
can I do it?

**Comment by sameersrivastava13** [comment]
@sufu786 Go ahead.
