### ISSUE TITLE
Update on readme.md

### ISSUE THREAD

**Issue by PrathmeshMutke** [sameersrivastava13/Vaccine-Tracker-App#6]
I want to update readme.md file and add some new features to it.
Plz assign me this issue

**Comment by PrathmeshMutke** [comment]
Devincept 21

**Comment by techabhi08** [comment]
Sir when will you upload the source code? Like will there be any issue assigned for this project or there are these 3 issues only?

**Comment by PrathmeshMutke** [comment]
I was busy in my exam preparation hence I got late here plz assign this issue someone

**Comment by sameersrivastava13** [comment]
Sure @PrathmeshMutke. Go ahead.

**Comment by sameersrivastava13** [comment]
@techabhi08 we will be creating more issues from now. As the program has started officially from today. So be active and grab the issues as soon as it is available or you can create your own issues if you have some idea and want to contribute.

**Comment by techabhi08** [comment]
Ok sir. Waiting for the same and will raise an issue if I will find any.
