### ISSUE TITLE
Bug : Image is not stable

### ISSUE THREAD

**Issue by ayushsoni1010** [sameersrivastava13/Vaccine-Tracker-App#62]
## Actual Behavior

The image is not properly stable

## Steps to close the Issue

Now, Image is properly stable and responsive on resize

## Check List (check only one)

- [x] Enhancement to the Older script.

## Specifications

  - Language Used:  CSS 

## Screenshots & Video
The left tab is mine in which the issue has been resolved
The right tab is the website

https://user-images.githubusercontent.com/76895975/126038327-1586fc4d-8244-4ca6-b602-da41767f10d5.mp4

**Comment by sameersrivastava13** [comment]
ok @ayushsoni1010. Assigning it to you. Also please see if there are any images which are not been used anywhere. Then remove that as well.

**Comment by ayushsoni1010** [comment]
> ok @ayushsoni1010. Assigning it to you. Also please see if there are any images which are not been used anywhere. Then remove that as well.

Okay I will see once again :)
