### ISSUE TITLE
chat bot

### ISSUE THREAD

**Issue by kumarishalini6** [sameersrivastava13/Vaccine-Tracker-App#72]
**Is your feature request related to a problem? Please describe.**
I want to make a chat bot
@sameersrivastava13 can i work on this issue??

**Comment by sameersrivastava13** [comment]
Wow @kumarishalini6. 🔥 It will be great if you can add the chat bot to the application.
Assigning it you, go ahead.

**Comment by sameersrivastava13** [comment]
Also @kumarishalini6, I have requested you to fetch the upstream in your previous PR. Please have a look so that I can merge it immediately. then you can start working on this.
