### ISSUE TITLE
Contact form Scroll button and text optimization

### ISSUE THREAD

**Issue by Biswa-bob** [sameersrivastava13/Vaccine-Tracker-App#75]
## Actual Behavior

text size is reduced.
scroll button is not smooth

## Steps to close the Issue

 _provide an overview, how you will solve the issue_

## Check List (check only one)

- [ ] Creating New Script.
- [ ] Enhacment to Older script.

## Specifications

  - Language Used: _ex: python_

**Comment by sameersrivastava13** [comment]
Assigning it to you @Biswa-bob. But you need to wait for the issue to be assigned to you. Then you should submit PR. Anyways, no issues. Go ahead
