### ISSUE TITLE
Add Lazy Loading

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#77]
### Description
Normally when a user opens a webpage, the entire page’s contents are downloaded and rendered in a single go. While this allows the browser to cache the web page, there’s no guarantee that the user will actually view all of the downloaded content.

Lazy loading a webpage reduces page weight, allowing for a quicker page load time. Add lazy loading to the application. Take reference [from here](https://css-tricks.com/the-complete-guide-to-lazy-loading-images/#method-1-trigger-the-image-load-using-javascript-events).

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

**Comment by dilroseR** [comment]
do you want lazy loading for only images ?

**Comment by sameersrivastava13** [comment]
Yes @dilroseR. Actually the images are creating issues and taking lot of time to load. I just want the page to load more quickly, reduce page weight and load time.

**Comment by dilroseR** [comment]
Can I try?
should apply lazy load to all images right?

**Comment by sameersrivastava13** [comment]
Yes go ahead @dilroseR. Do whatever you can in order to optimize the page load time.
