### ISSUE TITLE
Adding footer to contact Page

### ISSUE THREAD

**Issue by Biswa-bob** [sameersrivastava13/Vaccine-Tracker-App#80]
## Actual Behavior

Missing footer in contact page

## Steps to close the Issue

Adding footer to the contact page.

## Check List (check only one)

- [X] Enhacment to Older script.

## Specifications

  - Language Used: HTML, CSS

**Comment by sameersrivastava13** [comment]
Assigned @Biswa-bob

**Comment by Biswa-bob** [comment]
![contact-res](https://user-images.githubusercontent.com/56729624/126065807-226c3ebd-e7ad-44fc-b386-f409cca238e8.png)
![contact-res-1](https://user-images.githubusercontent.com/56729624/126065880-655b2019-58d4-4a67-a9c2-914b76741f23.png)

brother the page has gone complete out of track .. brother @sameersrivastava13  .

**Comment by sameersrivastava13** [comment]
@Biswa-bob Updates?
