### ISSUE TITLE
Design/Add a Page for project Contributors + Admin + Mentors 

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#81]
### Description
Design a Page or directly build a page for the Project Contributors, Mentors and Project admin. The page should have two parts:

Project Admin and Mentors (Name, photograph, GitHub & LinkedIn )
Contributors (Name, photograph, GitHub & LinkedIn )

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

**Comment by kumarishalini6** [comment]
@sameersrivastava13  can I work on this issue??

**Comment by sameersrivastava13** [comment]
@kumarishalini6 Go ahead.

**Comment by sameersrivastava13** [comment]
@kumarishalini6 updates?

**Comment by kumarishalini6** [comment]
> @kumarishalini6 updates?

Actually tomorrow is my last external can I start after that

**Comment by sameersrivastava13** [comment]
> > @kumarishalini6 updates?
> 
> Actually tomorrow is my last external can I start after that

Yea sure. no issues.

**Comment by Sejal2801** [comment]
Any Updates @kumarishalini6  ?

**Comment by kumarishalini6** [comment]
> Any Updates @kumarishalini6 ?

@Sejal2801  I am working on it

**Comment by sameersrivastava13** [comment]
> > Any Updates @kumarishalini6 ?
> 
> @Sejal2801 I am working on it

See you can make something like this :

Name, Photograph with LinkedIn and GitHub account. I made this page earlier for one of the projects. If you need any help you can DM me on slack. On mouse hover to the profile, the GitHub and LinkedIn icon can pop up.

![team](https://user-images.githubusercontent.com/56088741/126440624-915550d7-e040-4251-b9f8-9c6129766ccd.PNG)

**Comment by kumarishalini6** [comment]
> > > Any Updates @kumarishalini6 ?
> > 
> > 
> > @Sejal2801 I am working on it
> 
> See you can make something like this :
> 
> Name, Photograph with LinkedIn and GitHub account. I made this page earlier for one of the projects. If you need any help you can DM me on slack. On mouse hover to the profile, the GitHub and LinkedIn icon can pop up.
> 
> ![team](https://user-images.githubusercontent.com/56088741/126440624-915550d7-e040-4251-b9f8-9c6129766ccd.PNG)

Sure

**Comment by sameersrivastava13** [comment]
@kumarishalini6 It's almost a week. Any updates?

**Comment by kumarishalini6** [comment]
> @kumarishalini6 It's almost a week. Any updates?

Sorry but my laptop is not working it takes time if you want you can assign it to someone else.
