### ISSUE TITLE
Add a 404 Error page

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#83]
### Description
To add a 404 error page to keep a visitor on your site even if he/she hits a page that doesn't exist. Also to change the bad User experience to a positive one by adding some links to that 404 page so that the visitor can navigate to some other page.

### Tools

html
css

Take reference [from here](https://github.com/sameersrivastava13/404-Error-Pages).

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
yes

**Comment by dilroseR** [comment]
Can I Take up this?

**Comment by sameersrivastava13** [comment]
@dilroseR Assigned. I have also attached a link take help from that.
