### ISSUE TITLE
Adding Search by pin code page

### ISSUE THREAD

**Issue by Biswa-bob** [sameersrivastava13/Vaccine-Tracker-App#85]
## Actual Behavior

New Page - Search by Pin code.

## Steps to close the Issue

 _provide an overview, how you will solve the issue_

## Check List (check only one)

- [ ] Creating New Script.
- [ ] Enhacment to Older script.

## Specifications

  - Language Used: _ex: python_

**Comment by sameersrivastava13** [comment]
Go ahead @Biswa-bob .

**Comment by sameersrivastava13** [comment]
@Biswa-bob What about the another issue? Did you completed that?
