### ISSUE TITLE
Add a contributors Section 

### ISSUE THREAD

**Issue by Prakash-Haldar** [sameersrivastava13/Vaccine-Tracker-App#9]
The profile pic & name of the contributors will be shown in Readme section

**Comment by sameersrivastava13** [comment]
Sounds good @Prakash-Haldar. Go ahead.

**Comment by sameersrivastava13** [comment]
@Prakash-Haldar any updates?

**Comment by Prakash-Haldar** [comment]
Yess i m solving this issue

**Comment by Prakash-Haldar** [comment]
May I got The google form of "DevIncept.codes " Form @sameersrivastava13

**Comment by sameersrivastava13** [comment]
> May I got The google form of "DevIncept.codes " Form @sameersrivastava13

I have shared the form in the slack channel.

**Comment by Prakash-Haldar** [comment]
Plz share the link of Slack Channel @sameersrivastava13
