### ISSUE TITLE
image overlapping with chat bot window!!!

### ISSUE THREAD

**Issue by mayankmohak** [sameersrivastava13/Vaccine-Tracker-App#91]
## Actual Behavior

![image](https://user-images.githubusercontent.com/63801800/126437333-fb6ba8da-90f0-479e-8d96-38bf7bf7d814.png)
Image should be below chat bot.

## Steps to close the Issue

 _provide an overview, how you will solve the issue_

## Check List (check only one)

- [ ] Creating New Script.
- [x] Enhacment to Older script.

**Comment by sameersrivastava13** [comment]
@mayankmohak Yes please go ahead. The issue needs to be fixed asap.
