### ISSUE TITLE
Design/Add a Page for project Contributors + Admin + Mentors (HTML+CSS+Bootstrap)

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#94]
### Description
Design a Page or directly build a page for the Project Contributors, Mentors and Project admin. The page should have two parts:

Project Admin and Mentors (Name, photograph, GitHub & LinkedIn )
Contributors (Name, photograph, GitHub & LinkedIn )

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

**Comment by dilroseR** [comment]
can i do this?

**Comment by Sejal2801** [comment]
Yes @dilroseR Assigning it to you, Go ahead.

**Comment by sameersrivastava13** [comment]
@dilroseR Updates?

**Comment by dilroseR** [comment]
> @dilroseR Updates?
in progress will make a pr in 1-2 days
