### ISSUE TITLE
Add Search by pincode page. (HTML+CSS)

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#95]
### Description

The Two main features of our application are yet to be developed : 

1. Search by  Pincode
2. Search by District Name

Therefore build responsive frontend for the search by pincode feature for our application. It should have two input fields :  

1.  text field
2. date field

Take reference from [here.](https://www.sanjeevaniportal.xyz/vaccinetrackerbypincode)

  

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

**Comment by SukhbirSinghKhalsa** [comment]
Can I work on this frontend part?
this needs 2 sections:
1st section:
pincode 
date

2nd section:
state
district
date

if it is right, assign me this issue,please

**Comment by sameersrivastava13** [comment]
Yes @SukhbirSinghKhalsa. Go ahead. But keep posting the updates here. We want this asap.

**Comment by SukhbirSinghKhalsa** [comment]
please check, and revert for changes :
Link:(https://basicss.000webhostapp.com/pinbean.html)

the alerts will be removed, they are just added for testing purposes.

**Comment by Sejal2801** [comment]
Hey @SukhbirSinghKhalsa ,
Its looking very basic, Add some styling, and change the color combination also.

**Comment by sameersrivastava13** [comment]
> please check, and revert for changes :
> Link:(https://basicss.000webhostapp.com/pinbean.html)
> 
> the alerts will be removed, they are just added for testing purposes.

Similarly do for search by  district name page. @SukhbirSinghKhalsa
