### ISSUE TITLE
Add Search by district name page. (HTML+CSS) 

### ISSUE THREAD

**Issue by sameersrivastava13** [sameersrivastava13/Vaccine-Tracker-App#96]
### Description

The Two main features of our application are yet to be developed : 

1. Search by  Pincode
2. Search by District Name

Therefore build responsive frontend for the search by district name feature for our application. It should have 3 input fields :  

1.  Drop down list to select state name.
2.  Drop down list to select district name. 
3. date field

Take reference from [here.](https://www.sanjeevaniportal.xyz/vaccinetrackerbydistrict)

 
Have you read the [Contributing Guidelines on Pull Requests](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md)?
Yes

**Comment by akshay399** [comment]
can i work on this?

**Comment by sameersrivastava13** [comment]
Yes please @akshay399 . Go ahead. And keep posting the updates here.

**Comment by sameersrivastava13** [comment]
@akshay399 Updates?

**Comment by akshay399** [comment]
> @akshay399 Updates?

hi @sameersrivastava13 should i keep the background image of body same? 
![Search by district - Brave 27-07-2021 15_37_32](https://user-images.githubusercontent.com/55823965/127136762-e26de75f-eeef-40cf-bc8d-05964f5238ef.png)

**Comment by sameersrivastava13** [comment]
@akshay399 Its up to you. If you have any other design in mind. Do that.

**Comment by akshay399** [comment]
> @akshay399 Its up to you. If you have any other design in mind. Do that.

ok cool, i'll make it responsive and push it by evening

**Comment by sameersrivastava13** [comment]
> > @akshay399 Its up to you. If you have any other design in mind. Do that.
> 
> ok cool, i'll make it responsive and push it by evening

@akshay399 Waiting.

**Comment by akshay399** [comment]
> > > @akshay399 Its up to you. If you have any other design in mind. Do that.
> > 
> > 
> > ok cool, i'll make it responsive and push it by evening
> 
> @akshay399 Waiting.

hi @sameersrivastava13  sorry for the delay my wifi was acting up, [here](https://github.com/sameersrivastava13/Vaccine-Tracker-App/pull/101) is the PR i just made.
